POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1@test.com",
    "nickname": "test",
    "password": "test"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test"
}

###어드민
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "test"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTc2NTg1MTI4NSwiZXhwIjoxNzY1ODU0ODg1fQ.OxTOZhpKubj-usgSylsvJpsKFTGY6Nd4E3JnOlXfNpc

{
    "email": "test1@test.com",
    "password": "test"
}


###
POST http://localhost:3000/auth/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE3NjUyNjQ3MzQsImV4cCI6MTc2NjQ3NDMzNH0.mMSkuZMvtd1t0nB3M86Lq3QkJP9z8bxZ71F4euNingI

### 2) 내 챌린지 신청서 조회
GET http://localhost:3000/users/me/challenge-applications?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE3NjU1MjUzMjYsImV4cCI6MTc2NTUyODkyNn0.SgNcaZmUymzTMCe6Wo-qtBtjuIuVrqksjNXIT9XfnQE

### 3) 필터 적용된 내 챌린지 신청서 조회
GET http://localhost:3000/users/me/challenge-applications?page=1&pageSize=10&status=APPROVED
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE3NjU1MjUzMjYsImV4cCI6MTc2NTUyODkyNn0.SgNcaZmUymzTMCe6Wo-qtBtjuIuVrqksjNXIT9XfnQE

### 4) 내가 만든 챌린지 조회
GET http://localhost:3000/users/me/challenge?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE3NjU1MjUzMjYsImV4cCI6MTc2NTUyODkyNn0.SgNcaZmUymzTMCe6Wo-qtBtjuIuVrqksjNXIT9XfnQE

### 5) 필터 적용된 내 챌린지 조회
GET http://localhost:3000/users/me/challenge?page=1&pageSize=10&status=RECRUITING&category=Next.js
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE3NjU1MjUzMjYsImV4cCI6MTc2NTUyODkyNn0.SgNcaZmUymzTMCe6Wo-qtBtjuIuVrqksjNXIT9XfnQE
