POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "test1@test.com",
    "nickname": "test",
    "password": "test"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test"
}

###
POST http://localhost:3000/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2NDgzMDM0NSwiZXhwIjoxNzY1NDM1MTQ1fQ.t813hUL6jMVDZeRals62pS0rmhdR43jsJ7p7X3xXGLQ