POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1@test.com",
    "nickname": "test",
    "password": "test"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test"
}

###
POST http://localhost:3000/auth/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2NDg5NDg3MiwiZXhwIjoxNzY2MTA0NDcyfQ.on9P7HzlEGhOp9lfEseLLU1Qd-H3nfNXXr5OT2oFbLU